[workspace]
members = [
    "src/bolt",
    "src/ctl",
    "src/bench",
    "src/server",
    "src/storage",
    "src/logger",
    "src/cluster",
]
resolver = "2"

[profile.release]
panic = "abort"
lto = true
