[workspace]
members = [
    "src/bolt",
    "src/ctl",
    "src/bench",
    "src/server",
    "src/storage",
    "src/logger",
    "src/cluster",
]
default-members = ["src/bolt", "src/ctl"]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
