[package]
name = "cluster"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
bench = false

[dependencies]
tokio = { version = "1", features = ["sync", "net", "io-util", "time", "rt", "macros"] }
log = "0.4"
storage = { path = "../storage" }
futures = "0.3"
serde_json = "1"
